config/routes.rb
Rails.application.routes.draw do
  get 'replies/new'

  get 'replies/show'

  get 'replies/create'

  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :messages , only: [:create, :show, :new] do
    resources :replies, only: [:create,:show,:new]
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  has_many :replies

  validates :title, presence: true
  validates :content, presence: true
end

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  belongs_to :message

  validates :content, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :messages, :dependent => :destroy
  has_many :replies, :dependent => :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
  end
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @messages = Message.all
  end
end

app/controllers/homecontroller_controller.rb
class HomecontrollerController < ApplicationController
  def index;end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def new
    @message = Message.new
  end

  def create
    @message = current_user.messages.build(message_params)
    if @message.save
      flash[:success] = "Your message was created!"
      redirect_to message_path(@message)
    else
      render 'new'
    end
  end

  def show
    @message = Message.find(params[:id])
    @reply = Reply.new
    @replies = @message.replies
  end

  private

  def message_params
    params.require(:message).permit(:title, :content, :user_id)
  end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController

  def create
    @message = Message.find(params[:message_id])
    @reply = @message.replies.build(reply_params)
    @reply.user_id = current_user.id

    if @reply.save
      flash[:notice] = "Your reply was added!"
      redirect_to  message_path(@message)
    else
      render 'messages/show'
    end
  end

  private

  def reply_params
    params.require(:reply).permit(:content,:user_id,:message_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homecontroller_helper.rb
module HomecontrollerHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/views/home/index.html.erb
<h1> Welcome back, <%= current_user.username %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <table class="table table-hover">
      <tr>
        <th>Title</th>
        <th>Content</th>
        <th>Page</th>
        <th>Author</th>
      </tr>

      <% @messages.each do |msg| %>
      <tbody>
        <tr>
          <td>
            <%= msg.title %>
          </td>
          <td>
            <%= msg.content %>
          </td>
          <td>
            <%= link_to 'Show', message_path(msg) %>
          </td>
          <td>
            <small>Created <%= time_ago_in_words(msg.created_at) %> by <%= msg.creator.username %></small>
          </td>
        </tr>
      </tbody>

      <% end %>
    </table>
  </div>
</div>
<div class="col-md-4 col-md-offset-3">
  <p>
    <%= link_to 'Create a new message', new_message_path %>
  </p>
</div>

app/views/home/show.html.erb
<h1> Welcome back, <%= current_user.username %></h1>

<% current_user.messages.each do |msg| %>
<p>
  Title: <%= msg.title %><br>
  Content: <%= msg.content %>
</p>
<% end %>

<p>
  <%= link_to 'Create a new message', new_message_path %>
</p>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= link_to 'RailsBridge', "http://railsbridgenyc.org" %> - Message Board Project  |  2016
  </small>
  <nav>
    <ul>
      <!-- <li> link_to "About", about_path </li>
      <li> link_to "Contact", contact_path </li> -->
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <%= link_to "Message Board", unauthenticated_root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
      <li class="navbar-text">
        <%= current_user.email %>
      </li>
      <li>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <%= link_to 'sign out', destroy_user_session_path, method: :delete, class: "navbar-text" %>
      </li>
      <% else %>
      <li>
        <%= link_to 'sign in', user_session_path %>
      </li>
      <li>
        <%= link_to 'sign up', new_user_registration_path %>
      </li>
      <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Message Board</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
  <%= render 'layouts/footer' %>
</html>

app/views/messages/new.html.erb
<h1>Create a new message</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class='well'>
      <%= form_for(@message) do |f| %>

        <div class="control-group">
          <%= f.label :title %>
          <%= f.text_field :title %>
        </div>

        <div class="control-group">
          <%= f.label :content %>
          <%= f.text_field :content %>
        </div>

        <%= f.submit(@message.new_record? ? "Create message" : "Update message", class: 'btn btn-primary') %>

      <% end %>
    </div>
  </div>
</div>

app/views/messages/show.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <table class="table table-hover">
      <tr>
        <th>Title</th>
        <th>Content</th>
        <th>Author</th>
      </tr>
      <tbody>
        <tr>
          <td>
            <%= @message.title %>
          </td>
          <td>
            <%= @message.content %>
          </td>
          <td>
            <small>Created <%= time_ago_in_words(@message.created_at) %> by <%= @message.creator.username %></small>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
<br>
<br>
<div class="container">
<div class="col-md-6 col-md-offset-3">
<div class="well well-sm">
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <table class="table table-hover">
      <th>
        Reply
      </th>
      <th>
        Author
      </th>
      <% @replies.each do |rep| %>
      <tbody>
        <tr>
          <td>
            <%= rep.content %>
         </td>
         <td>
          <small>
             Created <%= time_ago_in_words(rep.created_at) %>
             by <%= rep.creator.username %>
          </small>
        </td>
       </tr>

      <% end %>
    </table>
  </div>
</div>
</div>
</div>

<div class="col-md-4 col-md-offset-3">
  <div class ="well well-sm">
    <%= form_for [@message, @reply] do |f| %>
      <%= f.text_area :content %>
      <br/>
      <%= f.submit "Create a reply", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
</div>
<div class="col-md-4 col-md-offset-5">
  <%= link_to 'back', :back %>
</div>